services:
  mcp-server:
    build: .
    ports:
      - "3030:3030"
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules